### ISSUE TITLE
eject when ripper.sh is complete

### ISSUE THREAD

**Issue by barnzdan** [rix1337/docker-ripper#3]
This is more related to the ubuntu image I think however Im interested to know if you've seen this.

When it comes time to eject the cdrom (/dev/sr0) I get the error:
"inappropriate ioctl for device"

I've tried to kill any procs using the device with fusker -k prior to the eject, I've tried a forced eject, I've tried patching the image. None of this seems to help. Have you seen this?

**Comment by barnzdan** [comment]
I was able to get past this problem by adding the sdparm utility to the Dockerfile -
apt-get -y --allow-unauthenticated install gddrescue ripit wget eject lame curl sdparm
Then running the following in ripper.sh after the cdrom is to be ejected -

mkdir -p "$DVDPATH"
 makemkvcon -r --decrypt --minlength=600 mkv disc:"$DVDNUM" all "$DVDPATH" >> $LOGFILE 2>&1
 echo "$(date "+%d.%m.%Y %T") : Done! Ejecting Disk"
 sleep 2
 sdparm --command=unlock /dev/sr0
 sleep 1
 sdparm --command=eject /dev/sr0

**Comment by rix1337** [comment]
It's been a while since I ripped my last disk & I have never seen the above error.

Glad to hear, this fixed it for you. If anyone else has this issue, I might implement your changes in the image.

And from a quick readup, it seems you are not using an ATA device. This might be the reason, why I haven't come across this issue. Could just be, that your drive operates differently because of SCSI

**Comment by barnzdan** [comment]
Ah, that makes sense now. Anyway, awesome work, this project REALLY helped with my setup!

**Comment by agster27** [comment]
I am getting a similar error. My drive will no eject. I am using an USB external drive case.

I'll see if I can try this fix.. I am new to Docker so I hope I wont mess it up too much :)
