### ISSUE TITLE
MakeMKV needs an update

### ISSUE THREAD

**Issue by James-Smart** [rix1337/docker-ripper#50]
Hi, I think MakeMKV needs updating from v1.15.1 to v1.15.2

as I am getting:
This application version is too old.  Please download the latest version at http://www.makemkv.com/ or enter a registration key to continue using the current version.","This application version is too old.  Please download the latest version at %1 or enter a registration key to continue using the current version.","http://www.makemkv.com/"

Thanks :)

**Comment by rix1337** [comment]
I triggered the build on docker hub. It just failed because phusion/baseimage:latest has become unavailable.
This commit https://github.com/rix1337/docker-ripper/commit/929149c532f0c9474a9acac30cce56f76bff32b4 hopefully fixes the build.

If that worked, the updated image should be available within 2 hours.

**Comment by James-Smart** [comment]
Thanks for the quick fix, Will confirm once its available

**Comment by rix1337** [comment]
Dang, phusion baseimage has changed. Ill try to fix this.

**Comment by rix1337** [comment]
Build successfully completed based on phusion/baseimage:0.9.22
