### ISSUE TITLE
update has broken container, missing makemkvcon ?

### ISSUE THREAD

**Issue by jcfrosty** [rix1337/docker-ripper#64]
*** Running /etc/my_init.d/ripper.sh...
Using this daily? Please sponsor me at https://github.com/sponsors/rix1337 - any amount counts!
08.04.2021 13:58:31 : Starting Ripper. Optical Discs will be detected and ripped within 60 seconds.
/config/ripper.sh: line 34: makemkvcon: command not found
08.04.2021 13:58:31 : Unexpected makemkvcon output:
/config/ripper.sh: line 34: makemkvcon: command not found
08.04.2021 13:59:31 : Unexpected makemkvcon output:
/config/ripper.sh: line 34: makemkvcon: command not found
08.04.2021 13:59:31 : Unexpected makemkvcon output:
/config/ripper.sh: line 34: makemkvcon: command not found
08.04.2021 14:00:31 : Unexpected makemkvcon output:
/config/ripper.sh: line 34: makemkvcon: command not found
08.04.2021 14:01:31 : Unexpected makemkvcon output:
/config/ripper.sh: line 34: makemkvcon: command not found
08.04.2021 14:02:31 : Unexpected makemkvcon output:
08.04.2021 14:02:31 : Too many errors, ejecting disk and aborting
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
/config/ripper.sh: line 57: makemkvcon: command not found
*** /etc/my_init.d/ripper.sh failed with status 1

The line its complaining about is 
INFO=$"`makemkvcon -r --cache=1 info disc:9999 | grep DRV:0`"

**Comment by rix1337** [comment]
Thanks for the Issue, I'll look into this when there is time.

**Comment by techie2000** [comment]
Confirmed reproducible :
```
*** Running /etc/my_init.d/ripper.sh...
Using this daily? Please sponsor me at https://github.com/sponsors/rix1337 - any amount counts!
08.04.2021 14:29:38 : Starting Ripper. Optical Discs will be detected and ripped within 60 seconds.
/config/ripper.sh: line 34: makemkvcon: command not found
08.04.2021 14:29:38 : Unexpected makemkvcon output:
/config/ripper.sh: line 34: makemkvcon: command not found
08.04.2021 14:30:38 : Unexpected makemkvcon output:
/config/ripper.sh: line 34: makemkvcon: command not found
08.04.2021 14:31:38 : Unexpected makemkvcon output:
/config/ripper.sh: line 34: makemkvcon: command not found
08.04.2021 14:32:38 : Unexpected makemkvcon output:
/config/ripper.sh: line 34: makemkvcon: command not found
08.04.2021 14:33:38 : Unexpected makemkvcon output:
08.04.2021 14:33:38 : Too many errors, ejecting disk and aborting
/config/ripper.sh: line 56: makemkvcon: command not found
*** /etc/my_init.d/ripper.sh failed with status 1


*** Killing all processes...
```

**Comment by rix1337** [comment]
Just use rix1337/docker-ripper:1.15.4 in the meantime.

**Comment by Johi-x** [comment]
i have the same issue and did some digging around; it seems like makemkv isn't installed due to the version check being broken since the changed the website for the forum page from https://www.makemkv.com/forum/viewtopic.php?f=3&t=224 to https://forum.makemkv.com/forum/viewtopic.php?f=3&t=224 . 
`    $ curl --silent 'https://www.makemkv.com/forum/viewtopic.php?f=3&t=224' `
`    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">    `
`    <html><head>    `
`    <title>301 Moved Permanently </title>    `
`    </head><body>   `
`    <h1>Moved Permanently/</h1>   `
`    <p>The document has moved <a href="https://forum.makemkv.com/forum/viewtopic.php?f=3&amp;t=224">here</a>.</p>   `
`    </body></html> `

` $ curl --silent 'https://forum.makemkv.com/forum/viewtopic.php?f=3&t=224' | grep MakeMKV.*.for.Linux.is | head -n 1 | sed -e 's/.*MakeMKV //g' -e 's/ .*//g'    `
`1.16.3
    `
Since 1.16.3 is out now the older makemkv version doesn't work for me anymore. from the ripper.log:
`MSG:5021,131332,1,"This application version is too old.  Please download the latest version at http://www.makemkv.com/ or enter a registration key to continue using the current version."`
so it just creates empty folders with the DVD Title

**Comment by rix1337** [comment]
Hm, that seems like an easy fix. I'm more than glad to allow willing collaborators to join this project.

**Comment by rix1337** [comment]
Build will be done in ~15 minutes.
