### ISSUE TITLE
abcde config

### ISSUE THREAD

**Issue by VK-87** [rix1337/docker-ripper#70]
in ripper.sh abcde is called as following;
 /usr/bin/abcde -d "$DRIVE" -c /config/abcde.conf -N -x -l >> $LOGFILE 2>&1

Unfortunally de abcde.conf is not located in /config but in /ripper

in the abcde.conf the location of the output is;
# Give the base location here for the encoded music files.
OUTPUTDIR="$STORAGE_CD"    

But $STORAGE_CD is nog being used. so ABCDE doesn't work

$storage_cd can be replaced by /out/Ripper/CD

**Comment by rix1337** [comment]
Best send a pull request fixing the issue.
I'll review it

**Comment by VK-87** [comment]
just send a pull request

**Comment by rix1337** [comment]
currently no pull request open from you.

**Comment by VK-87** [comment]
hopefully now it works..

**Comment by rix1337** [comment]
closed by #71 
thanks

**Comment by jeprecated** [comment]
The documentation still references the abcde.conf file as if it is in the config/ folder https://github.com/rix1337/docker-ripper#how-do-i-customize-the-audio-ripping-output 

I was attempting to change the abcde.conf file, and I see I have to change the location to the config folder in order for it to remain persistent and not in the docker files. Then I need to point the ripper.sh file to that config file. But there are two ripper.sh files: one in config/ and one in ripper/ :thinking: the docs refer to the file in config folder, so I presume that is right? But it is rather confusing. 

Any help sorting this out would be appreciated.

**Comment by edgd1er** [comment]
at boot time, the init stage will copy some files from /config to /ripper. Should you need persistent changes, modifying files in /config should be the solution.

https://github.com/rix1337/docker-ripper/blob/0d6f7b7c8a8dd63638f40d26bc595ed102f42734/root/etc/my_init.d/ripper.sh#L31

**Comment by jeprecated** [comment]
Ah I see. Thanks for the clarification. So the /config/abcde.conf file is the only one that matters.

*But then* I can also see that ripper.sh gets moved from /ripper to /config if it does not yet exist. So we have this weird setup that moves /ripper/ripper.sh to /config/ripper.sh the first time, and moves /config/abcde.conf to /ripper/abcde.conf _every time_, just so the ripper.sh can reference the abcde.conf in  /ripper :confounded: 

*Surely* it would be a lot more straightforward to simply do the same for the abcde.conf file as is done for ripper.sh - make sure the default one is there and use the one in /config. 
- The abcde.conf is created by default
     - Available for people to edit
     - Persistent
- Dependencies live next to each other
- The docs are correct again (that the file is located at /config)
- /ripper only gets used on the first init and never again (rather than being read each time for the abcde.conf file).

Seems convoluted, the way it is done now :man_shrugging:

**Comment by rix1337** [comment]
You are more than welcome to send a pull request with an improvement.
