### ISSUE TITLE
Error while trying to scan a DVD

### ISSUE THREAD

**Issue by JustM3dium** [rix1337/docker-ripper#74]
When I try to scan a DVD I get an error in the log and the scan fails. The error reads "This application version is too old.  Please download the latest version at http://www.makemkv.com/ or enter a registration key to continue using the current version.", "This application version is too old.  Please download the latest version at %1 or enter a registration key to continue using the current version.", "http://www.makemkv.com/"
I already tried to set the beta key from the makemkv page as documented in the readme, but this did not lead to any improvement. I also tried to build the Docker image myself, but the same error occurs. The day before yesterday I could scan DVDs so something must have changed yesterday/today.
I hope you can help me further.

**Comment by edgd1er** [comment]
Hi @JustM3dium

The beta key is valid until end of July. Even rebuilding the image will fail until the ppa:heyarje/makemkv-beta repository is updated with latest beta 1.16.4. current version from this ppa repository is 17 weeks old, not sure it's version 1.16.4

You can either wait for it to be updated or look for a fork with an image build from makemv sources. ;)
as I'm no makemkv expert the root cause could be something else.

You may have tried to remove settings.conf to force the container to set the key with the beta serial on next restart.

**Comment by rix1337** [comment]
https://github.com/rix1337/docker-ripper#makemkv-needs-an-update

**Comment by rix1337** [comment]
update triggered

**Comment by rix1337** [comment]
@edgd1er could be right though. The PPA potentially needs an update first
