### ISSUE TITLE
Consider adding notification/alerts.

### ISSUE THREAD

**Issue by SimonBrooker** [rix1337/docker-ripper#79]
It would seem this is quite popular with people digitizing their physical media libraries. Some of these libraries will likely run into hundreds of discs. With DVDs and Bluray especially, each disk can take a significant and often varying amount of time from film to film. It would be helpful if there was a notification sent on completion/error, during the eject process maybe. This would allow digitizers to shoot back and change the disc when prompted.

**Some ideas for notifications**

- Web Push
- Email
- Pushbullet
- Pushover
- Gotify
- Web Hook

**Comment by rix1337** [comment]
I will not actively develop this, since there is no real sponsor base for this project. I am happy with it as-is.

I have added notifications for various clients in another project: https://github.com/rix1337/FeedCrawler/blob/master/feedcrawler/notifiers.py
* Home Assistant
* Telegram
* Pushbullet
* Pushover

If you want to implement something like this, just copy-paste my code from FeedCrawler, make it standalone and adapt it to your needs. I'll gladly accept a pull request.

**Comment by rix1337** [comment]
Issue is IDLE. Reponeing upon pull request.

**Comment by jeprecated** [comment]
@SimonBrooker I had the same issue. I got notifications by monitoring the logs for "Disk Ejected" or "Ejecting Disk" using Howler https://github.com/Zggis/howler :+1:

**Comment by rix1337** [comment]
Having basically no community support / sponsorships for this project, my focus lies elsewhere.

Send over a pull request if you want.

I will try and keep the status quo running

**Comment by rix1337** [comment]
Using howler is a great workaround though!
